### ISSUE TITLE
Have you had luck making this work in neovim?

### ISSUE THREAD

**Issue by danjessen** [Kibadda/tree-sitter-smarty#1]
Hi
I appreciate the repository. But I'm wondering if you managed to make it work in something like neovim? 
![Screenshot 2023-11-08 at 09 17 13](https://github.com/Kibadda/tree-sitter-smarty/assets/351447/22b6898f-0c28-4d18-b818-2479119e90b1)

I could be setting it up wrong.

**Comment by Kibadda** [comment]
Hi
I have not used this for some time now. I believe some parts are broken currently. I try to look into it.

**Comment by Kibadda** [comment]
I pushed some updates and included an example in the README.md

**Comment by danjessen** [comment]
Thank you. I'll check it out

**Comment by danjessen** [comment]
@Kibadda thx. Not perfect. But definitely better
<img width="286" alt="Screenshot 2023-11-10 at 08 29 55" src="https://github.com/Kibadda/tree-sitter-smarty/assets/351447/6a05bd19-87d1-40e8-ac8d-c1d545ee4b5b">
